[project]
name = "mallennlp"
loglevel = "INFO"

[server]
image = "epwalsh/allennlp-manager:0.0.1"
port = 5000
secret = "ce932a8e69c61ad946ab8d0a3299a1f5d8024d33418fa084"
concurrency = 10
memory = 1024
cpus = 0.5
