[project]
name = "example-project"
loglevel = "DEBUG"
display_name = "My Project"

[server]
port = 5000
secret = "c6bd1b93cb0cefb3b14e6b8ba60d239b19594f0c35691d33"
workers = 4
worker_connections = 10000
imports = [ "hello_world",]
